describe('Simple stack tests', () => {
  it('Login flow', () => {
    cy.clearAllCookies()
    cy.clearAllLocalStorage()
    cy.visit('/')
    cy.get('h1').contains('Team')
    cy.get('button').contains('Log in').click()
    cy.url().should('include', '/signin')
    cy.get('input[type="email"]').type('l1@gmail.com')
    cy.get('input[type="password"]').type('1234')
    cy.get('button').contains('Submit').click({timeout: 7500})
    cy.get('a[href*="dashboard"]').should('be.visible')
  })

  it('Dashboard flow', () => {
    cy.visit('/65e8d7d19177805d42a51cfb/dashboard')
    cy.get('h1').contains('Dashboard')
    cy.get('h2').contains('Invite your first user')
    cy.get('p').contains('Add your team members and external users.')
    cy.get('div.cursor-pointer.items-center').contains(' Copy invite link')
  })
  it('Employee flow', () => {
    cy.get('.mb-1 a[href*="employees"]').click()
    cy.url().should('contain', 'employees')
    cy.get('h1').contains('Employees')
    cy.get('table').should('be.visible')
  })
  it('Team roles flow', () => {
    cy.get('.mb-1 a[href*="teamroles"]').click()
    cy.url().should('contain', 'teamroles')
    cy.get('h1').contains('Team roles')
    cy.get('button.bg-slate-900').contains('New team')
    cy.get('table').should('be.visible')
  })
  it('Departments flow', () => {
    cy.get('.mb-1 a[href*="departments"]').click()
    cy.url().should('contain', 'departments')
    cy.get('h1').contains('Departments')
    cy.get('button.bg-slate-900').contains('New department')
    cy.get('table').should('be.visible')
  })
  it('My department flow', () => {
    cy.get('.mb-1 a[href*="mydepartment"]').click()
    cy.url().should('contain', 'mydepartment')
    cy.get('h3').contains('Projects')
    cy.get('table').should('be.visible')
    cy.get('a[href*="projects/65f0b82099810eac3c96d267"]').click()
    cy.url().should('contain', '65f0b82099810eac3c96d267')
  })
  it('Skill assignments flow', () => {
    cy.get('.mb-1 a[href*="skillassignment"]').click()
    cy.url().should('contain', 'skillassignment')
    cy.get('h1').contains('Skill Assignment')
    cy.get('table').should('be.visible')
  })
  it('Skills (view) flow', () => {
    cy.get('.mb-1 a[href*="skills"]').click()
    cy.url().should('contain', 'skills')
    cy.get('h1').contains('Skills')
    cy.get('table').should('be.visible')
    cy.get('a[href*="new"]').click()
    cy.url().should('contain', 'new')
    cy.get('label').should('be.visible')
  })
  it('Skills (categories) flow', () => {
    cy.get('.mb-1 a[href*="skills"]').click()
    cy.url().should('contain', 'skills')
    cy.get('h1').contains('Skills')
    cy.get('table').should('be.visible')
    cy.get('a[href*="viewskillcategories"]').click()
    cy.url().should('contain', 'viewskillcategories')
    cy.get('a[href*="newcategory"]').click()
    cy.get('label').should('be.visible')
  })
  it('Projects flow', () => {
    cy.get('.mb-1 a[href*="projects"]').click()
    cy.url().should('contain', 'projects')
    cy.get('h1').contains('Projects')
    cy.get('table').should('be.visible')
    cy.get('a[href*="new"]').contains('New project')
    
  })
  it('My projects flow', () => {
    cy.get('a[href*="myprojects"]').contains('My Projects').click()
    cy.get('h1').contains('My projects')
    cy.get('.grid').should('be.visible')
  })
  it('Assign members flow', () => {
    cy.get('.mb-1 a[href*="departmentassign"]').click()
    cy.get('h1').should('contain', 'Members')
    cy.get('table').should('be.visible')
  })
  it('Proposals flow', () => {
    cy.get('.mb-1 a[href*="proposals"]').click()
    cy.get('h1').contains('Proposals')
    cy.get('button[role="tab"]').contains('Assignments')
    cy.get('button[role="tab"]').contains('Deallocations')
  })
})